63011212019 อาทิตย์ ทวีบท 17/08/65

In [7]:
from keras.datasets import fashion_mnist
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

(x_train,y_train),(x_test,y_test) = fashion_mnist.load_data()

train_x = np.zeros((x_train.shape[0], 28 * 28))
for i,x in enumerate(x_train):
  train_x[i] = x.reshape(1,28 * 28)

knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(train_x, y_train)

KNeighborsClassifier()

In [8]:
test_x = np.zeros((x_test.shape[0], 28*28))
for i,x in enumerate(x_test):
  test_x[i] = x.reshape(1,28 * 28)
predict = knn.predict(test_x[0 : 50])
true = y_test[0 : 50]
print(predict)
print(true)

[9 2 1 1 6 1 4 6 5 7 4 5 5 3 4 1 2 6 8 0 2 7 7 9 1 2 6 0 9 3 8 8 3 3 8 0 7
 5 7 9 0 1 6 9 6 7 2 1 2 2]
[9 2 1 1 6 1 4 6 5 7 4 5 7 3 4 1 2 4 8 0 2 5 7 9 1 4 6 0 9 3 8 8 3 3 8 0 7
 5 7 9 6 1 3 7 6 7 2 1 2 2]


In [31]:
cm = np.zeros((10,10))
for i in range(50):
  p = predict[i]
  t = true[i]
  cm[p][t] = cm[p][t] + 1
print(cm)
print(sum(sum(cm)))
total = sum(sum(cm))

acc_sum = 0
acc = 0
for i in range(10):
  acc_sum += cm[i][i]
acc = acc_sum/total
print('accuaracy : ' + str(acc))

precision = np.zeros((10,1), dtype = np.float32)
recall = np.zeros((10,1), dtype = np.float32)
total_p = 0
total_c = 0

for i in range(10):
  precision[i] = cm[i][i]/sum(cm[i,:])
  recall[i] = cm[i][i]/sum(cm[:,i])
  total_p += 1/precision[i]
  total_c += 1/precision[i]

l_precision = 10/total_p
l_recall= 10/total_c
#print(l_precision, l_recall)

f1 = 2 * (l_precision * l_recall) / (l_recall + l_precision)
#print(f1)

print('precision : ' + str(l_precision[0]))
print('recall : ' + str(l_recall[0]))
print('f1 : ' + str(f1[0]))

#print(precision)
#print('------------------------------')
#print(recall)

[[3. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 7. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 6. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 4.]]
50.0
accuaracy : 0.86
precision : 0.84865624
recall : 0.84865624
f1 : 0.84865624
